SELECT TOP 10 DT_CA_ID AS CA_ID, DT_CA_BAL AS CA_BAL, (sum(DT_HS_QTY * DT_LT_PRICE)) as RES_SUM

FROM [tpcE].[dbo].[DTT2T3T8]

WHERE DT_CA_C_ID = 4300000007 and DT_HS_S_SYMB IS NOT NULL

GROUP BY DT_CA_ID, DT_CA_BAL

ORDER BY 3 ASC


SELECT TOP 10 DT_CA_ID, DT_CA_BAL, DT_HS_QTY, DT_LT_PRICE

FROM [tpcE].[dbo].[DTT2T3T8]

WHERE DT_CA_C_ID = 4300000007 and DT_HS_S_SYMB IS NOT NULL

